name: epw

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and push Docker container
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push multi-architecture Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile  # Path to your Dockerfile
          platforms: linux/amd64,linux/arm/v7
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: |
            ghcr.io/erikpersson0884/epw:latest
          labels: |
            org.opencontainers.image.source=https://github.com/erikpersson0884/epw

      - name: Create and push manifest list
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker manifest create ghcr.io/erikpersson0884/epw:latest \
            ghcr.io/erikpersson0884/epw:latest-amd64 \
            --amend ghcr.io/erikpersson0884/epw:latest-arm-v7
          
          docker manifest annotate ghcr.io/erikpersson0884/epw:latest ghcr.io/erikpersson0884/epw:latest --os linux --arch amd64
          docker manifest annotate ghcr.io/erikpersson0884/epw:latest ghcr.io/erikpersson0884/epw:latest-arm-v7 --os linux --arch arm --variant v7
          
          docker manifest push ghcr.io/erikpersson0884/epw:latest
